/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ListBoxItem : ContentControl {
  private HandleRef swigCPtr;

  public ListBoxItem(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.ListBoxItem_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(ListBoxItem obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ListBoxItem() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          if (Noesis.Kernel.IsInitialized()) { NoesisGUI_PINVOKE.delete_ListBoxItem(swigCPtr);}
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }


  public delegate void SelectedDelegate(BaseComponent arg0,   RoutedEventArgs arg1);
  public event SelectedDelegate Selected
  {
    add
    {
      lock (this)
      {
        if (!_Selected.ContainsKey(swigCPtr.Handle))
        {
          _Selected.Add(swigCPtr.Handle, null);

          NoesisGUI_PINVOKE.BindEvent_ListBoxItem_Selected(RaiseSelected, swigCPtr.Handle);
          #if UNITY_EDITOR
          if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
          #endif
        }

        _Selected[swigCPtr.Handle] += value;
      }
    }
    remove
    {
      lock (this)
      {
        if (!_Selected.ContainsKey(swigCPtr.Handle))
        {
          throw new System.Exception("Delegate not found");
        }

        _Selected[swigCPtr.Handle] -= value;

        if (_Selected[swigCPtr.Handle] == null)
        {
          NoesisGUI_PINVOKE.UnbindEvent_ListBoxItem_Selected(RaiseSelected, swigCPtr.Handle);
          #if UNITY_EDITOR
          if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
          #endif

          _Selected.Remove(swigCPtr.Handle);
        }
      }
    }
  }

  public delegate void DelegateRaiseSelected(IntPtr cPtr, IntPtr arg0, IntPtr arg1);

  [MonoPInvokeCallback(typeof(DelegateRaiseSelected))]
  private static void RaiseSelected(IntPtr cPtr, IntPtr arg0, IntPtr arg1)
  {
    if (!_Selected.ContainsKey(cPtr))
    {
      throw new System.Exception("Delegate not found");
    }

    if (_Selected[cPtr] != null)
    {
      _Selected[cPtr](new BaseComponent(arg0, false), new   RoutedEventArgs(arg1, false));
    }
  }

  static System.Collections.Generic.Dictionary<System.IntPtr, SelectedDelegate> _Selected =
      new System.Collections.Generic.Dictionary<System.IntPtr, SelectedDelegate>();


  public delegate void UnselectedDelegate(BaseComponent arg0,   RoutedEventArgs arg1);
  public event UnselectedDelegate Unselected
  {
    add
    {
      lock (this)
      {
        if (!_Unselected.ContainsKey(swigCPtr.Handle))
        {
          _Unselected.Add(swigCPtr.Handle, null);

          NoesisGUI_PINVOKE.BindEvent_ListBoxItem_Unselected(RaiseUnselected, swigCPtr.Handle);
          #if UNITY_EDITOR
          if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
          #endif
        }

        _Unselected[swigCPtr.Handle] += value;
      }
    }
    remove
    {
      lock (this)
      {
        if (!_Unselected.ContainsKey(swigCPtr.Handle))
        {
          throw new System.Exception("Delegate not found");
        }

        _Unselected[swigCPtr.Handle] -= value;

        if (_Unselected[swigCPtr.Handle] == null)
        {
          NoesisGUI_PINVOKE.UnbindEvent_ListBoxItem_Unselected(RaiseUnselected, swigCPtr.Handle);
          #if UNITY_EDITOR
          if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
          #endif

          _Unselected.Remove(swigCPtr.Handle);
        }
      }
    }
  }

  public delegate void DelegateRaiseUnselected(IntPtr cPtr, IntPtr arg0, IntPtr arg1);

  [MonoPInvokeCallback(typeof(DelegateRaiseUnselected))]
  private static void RaiseUnselected(IntPtr cPtr, IntPtr arg0, IntPtr arg1)
  {
    if (!_Unselected.ContainsKey(cPtr))
    {
      throw new System.Exception("Delegate not found");
    }

    if (_Unselected[cPtr] != null)
    {
      _Unselected[cPtr](new BaseComponent(arg0, false), new   RoutedEventArgs(arg1, false));
    }
  }

  static System.Collections.Generic.Dictionary<System.IntPtr, UnselectedDelegate> _Unselected =
      new System.Collections.Generic.Dictionary<System.IntPtr, UnselectedDelegate>();


  public ListBoxItem() : this(NoesisGUI_PINVOKE.new_ListBoxItem(), true) {
    #if UNITY_EDITOR
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public bool GetIsSelected() {
    bool ret = NoesisGUI_PINVOKE.ListBoxItem_GetIsSelected(swigCPtr);
    #if UNITY_EDITOR
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  public void SetIsSelected(bool value) {
    NoesisGUI_PINVOKE.ListBoxItem_SetIsSelected(swigCPtr, value);
    #if UNITY_EDITOR
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public static DependencyProperty IsSelectedProperty {
    set {
      NoesisGUI_PINVOKE.ListBoxItem_IsSelectedProperty_set(DependencyProperty.getCPtr(value));
      #if UNITY_EDITOR
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
    } 
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ListBoxItem_IsSelectedProperty_get();
      DependencyProperty ret = (cPtr == IntPtr.Zero) ? null : new DependencyProperty(cPtr, false);
      #if UNITY_EDITOR
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      #endif
      return ret;
    } 
  }

  public new static void Extend(System.Type type) {
    IntPtr typeClassPtr = Noesis.Extend.GetPtrForType(type);
    NoesisGUI_PINVOKE.Extend_ListBoxItem(typeClassPtr);
    #if UNITY_EDITOR
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public new static bool CheckType(BaseComponent val) {
    IntPtr valPtr = BaseComponent.getCPtr(val).Handle;
    return NoesisGUI_PINVOKE.CheckType_ListBoxItem(valPtr);
  }

}

}

