/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class NullableBool : BaseNullable {
  private HandleRef swigCPtr;

  public NullableBool(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.NullableBool_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(NullableBool obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~NullableBool() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          if (Noesis.Kernel.IsInitialized()) { NoesisGUI_PINVOKE.delete_NullableBool(swigCPtr); }
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public NullableBool() : this(NoesisGUI_PINVOKE.new_NullableBool__SWIG_0(), true) {
  }

  public NullableBool(bool value) : this(NoesisGUI_PINVOKE.new_NullableBool__(value), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetValue() {
    bool ret = NoesisGUI_PINVOKE.NullableBool_GetValue__(swigCPtr);
    return ret;
  }

  public void SetValue(bool value)
  {
      NoesisGUI_PINVOKE.NullableBool_SetValue__(swigCPtr, value);
  }

}

}

