/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class NullableInt32 : BaseNullable {
  private HandleRef swigCPtr;

  public NullableInt32(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.NullableInt32_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(NullableInt32 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~NullableInt32() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          if (Noesis.Kernel.IsInitialized()) { NoesisGUI_PINVOKE.delete_NullableInt32(swigCPtr); }
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public NullableInt32() : this(NoesisGUI_PINVOKE.new_NullableInt32__SWIG_0(), true) {
  }

  public NullableInt32(int value) : this(NoesisGUI_PINVOKE.new_NullableInt32__(value), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetValue()
  {
      int ret = NoesisGUI_PINVOKE.NullableInt32_GetValue__(swigCPtr);
      return ret;
  }

  public void SetValue(int value)
  {
      NoesisGUI_PINVOKE.NullableInt32_SetValue__(swigCPtr, value);
  }

}

}

